feat: ignoreIfEmpty flag setting
ethereum/grid-ui pull request #159
Opened 2019-11-11 17:18 UTC by ryanio

#### What does it do? Does it close any issues?
Introduces property `ignoreIfEmpty` to flag settings.

See https://github.com/ethereum/grid/pull/518

Closes one of the issues in https://github.com/ethereum/grid/issues/512

2019-11-11 19:41 UTC, evertonfraga requested changes
Looks good!
please add test cases to this new feature: https://github.com/ethereum/grid-ui/blob/dev/src/test/settings.test.js

2019-11-11 19:41 UTC, evertonfraga commented on src/components/Plugins/PluginConfig/index.js
> +      }
yay! :)

2019-11-11 20:27 UTC, ryanio commented
> Looks good!
> please add test cases to this new feature: https://github.com/ethereum/grid-ui/blob/dev/src/test/settings.test.js

Thanks for the reminder 👍

Here they are:
<img width="607" alt="Screen Shot 2019-11-11 at 12 26 27 PM" src="https://user-images.githubusercontent.com/22116/68618640-a04cce80-047e-11ea-9b0c-9f94b552e332.png">

2019-11-11 21:11 UTC, evertonfraga commented
That's great, thanks.

Because of this `split()` call [here](https://github.com/ethereum/grid-ui/pull/159/files#diff-aea0fe63fc22cd8674041c51eafafba3R12), I think you should add a test if spaces are added to the input.

2019-11-15 22:57 UTC, wolovim approved these changes

2019-11-15 22:58 UTC, merged